### ISSUE TITLE
Question on usage of rga

### ISSUE THREAD

**Issue by MockbaTheBorg** [JeffyCN/drm-rga-demo#1]
Hi Jeffy,

Sorry to use this issue to start a conversation.
I am trying to get any information/help/light on the usage of /dev/rga2.
I have this device which is based on the Radxa Rock2 SoM, processor rk3288, and it exposes /dev/rga2 (it is running Linux, seems to be a port of Jessie).
However I am not able to find any working examples of usage of rga2, only rga.
I have tried making a test program which works fine on my Radxa Rock Pro (with /dev/rga), but on my Akai Force (with /dev/rga2) it doesn't work.
I make the correct adaptations when I move from one to the other, as the command IDs are different.
On the Force it fails and gives me version as being 0.000.
Here is the code I used:
```
#include <sys/ioctl.h>
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>

#define RGA2_BLIT_SYNC	 0x6017
#define RGA2_BLIT_ASYNC  0x6018
#define RGA2_FLUSH       0x6019
#define RGA2_GET_RESULT  0x601a
#define RGA2_GET_VERSION 0x601b

int main() {
	int fd=-1;
	int ret;
	float mVersion;
	char buf[30] = {};

	printf("Opening /dev/rga2 ... ");
	fd = open("/dev/rga2", O_RDWR, 0);
	if(fd < 0) {
		printf("Error! (%d)\n", fd);
		exit(1);
	} else {
		printf("Ok! (%d)\n", fd);
	}

	printf("Getting version ... ");
	ret = ioctl(fd, RGA2_GET_VERSION, buf);
	printf("Ok! (%d)\n", ret);
	mVersion = atof(buf);
	printf("Version: %f\n", mVersion);
}
```
I don't know what else to do. So I am shooting in the dark hoping that someone will be able to help.
Other applications that rotate the screen are working fine, but I do not have source for them, I only see the reference to /dev/rga2 inside the hex editor/disassembly.
Any help is much appreciated. 

Thank you very much,
Marcelo.

**Comment by JeffyCN** [comment]
Hi,

Sorry, i have no idea about /dev/rga2, the kernel driver & user library all using /dev/rga for rga2 block.

Here are some thoughts about it:
1/ There're a few blogs mentioned /dev/rga2 for firefly rk3399(https://www.programmersought.com/article/1153489470/), maybe you can ask it at the firefly forum?
2/ Maybe send a mail about it to putin.li@rock-chips.com(maintainer of current rga user library and kernel driver)
3/ If you have the kernel source code, maybe try to replace the driver(and dts) with Rockchip BSP 4.4 kernel(drivers/video/rockchip/rga*)
4/ If you have the user space source code, there might be a librga or other user space library, which might provide APIs and demos.

**Comment by MockbaTheBorg** [comment]
I will give it all a try, thank you very much.
Have a wonderful day.

Cheers,
Marcelo
